root: true
extends:
  - plugin:markdown/recommended
plugins:
  - markdown
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  indent: [error, 2, { SwitchCase: 1 }]
  no-trailing-spaces: error
